backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: Workout
        name: workout
        fields:
          - label: Sessions
            name: session_list
            widget: list
            fields:
              - label: Header
                name: header
                widget: text
              - label: Exercises
                name: exercise_list
                widget: list
                fields:
                  - label: Header
                    name: header
                    widget: text
                  - label: URL
                    name: url
                    widget: text
                  - label: Target
                    name: target
                    widget: text
                  - label: Reps
                    name: reps
                    widget: text
                  - label: Weight
                    name: weight
                    widget: text
                  - label: Alternate
                    name: alternate
                    widget: boolean
                    default: false
