backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - label: Pages
    name: pages
    files:
      - file: content/_index.md
        label: Workout
        name: workout
        fields:
          - label: Sessions
            name: session_list
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Exercises
                name: exercise_list
                widget: list
                fields:
                  - label: Heading
                    name: heading
                    widget: string
                    required: true
                  - label: URL
                    name: url
                    widget: string
                    required: false
                  - label: Target
                    name: target
                    widget: string
                    required: false
                  - label: Reps
                    name: reps
                    widget: string
                    required: false
                  - label: Weight
                    name: weight
                    widget: string
                    required: false
                  - label: Alternate
                    name: alternate
                    widget: boolean
                    default: false
                    required: false
